//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace action_gw.PhoneCalls {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetPhoneCallsData", Namespace="http://schemas.datacontract.org/2004/07/PublicServiceForPartners.DataContracts")]
    [System.SerializableAttribute()]
    public partial class GetPhoneCallsData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BitrixIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid CompanyIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateEventField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EventNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> EventNrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KppField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OverviewField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.Guid> ParentPhoneCallIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid PhoneCallIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneCallNrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.Guid> PrimaryPhoneCallIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> PriorityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductEventField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ScheduledStartField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> TimeDifferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> TypeEventField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BitrixId {
            get {
                return this.BitrixIdField;
            }
            set {
                if ((object.ReferenceEquals(this.BitrixIdField, value) != true)) {
                    this.BitrixIdField = value;
                    this.RaisePropertyChanged("BitrixId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid CompanyId {
            get {
                return this.CompanyIdField;
            }
            set {
                if ((this.CompanyIdField.Equals(value) != true)) {
                    this.CompanyIdField = value;
                    this.RaisePropertyChanged("CompanyId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CompanyName {
            get {
                return this.CompanyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyNameField, value) != true)) {
                    this.CompanyNameField = value;
                    this.RaisePropertyChanged("CompanyName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerName {
            get {
                return this.CustomerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerNameField, value) != true)) {
                    this.CustomerNameField = value;
                    this.RaisePropertyChanged("CustomerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateEvent {
            get {
                return this.DateEventField;
            }
            set {
                if ((this.DateEventField.Equals(value) != true)) {
                    this.DateEventField = value;
                    this.RaisePropertyChanged("DateEvent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EventName {
            get {
                return this.EventNameField;
            }
            set {
                if ((object.ReferenceEquals(this.EventNameField, value) != true)) {
                    this.EventNameField = value;
                    this.RaisePropertyChanged("EventName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> EventNr {
            get {
                return this.EventNrField;
            }
            set {
                if ((this.EventNrField.Equals(value) != true)) {
                    this.EventNrField = value;
                    this.RaisePropertyChanged("EventNr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Inn {
            get {
                return this.InnField;
            }
            set {
                if ((object.ReferenceEquals(this.InnField, value) != true)) {
                    this.InnField = value;
                    this.RaisePropertyChanged("Inn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Kpp {
            get {
                return this.KppField;
            }
            set {
                if ((object.ReferenceEquals(this.KppField, value) != true)) {
                    this.KppField = value;
                    this.RaisePropertyChanged("Kpp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Overview {
            get {
                return this.OverviewField;
            }
            set {
                if ((object.ReferenceEquals(this.OverviewField, value) != true)) {
                    this.OverviewField = value;
                    this.RaisePropertyChanged("Overview");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> ParentPhoneCallId {
            get {
                return this.ParentPhoneCallIdField;
            }
            set {
                if ((this.ParentPhoneCallIdField.Equals(value) != true)) {
                    this.ParentPhoneCallIdField = value;
                    this.RaisePropertyChanged("ParentPhoneCallId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid PhoneCallId {
            get {
                return this.PhoneCallIdField;
            }
            set {
                if ((this.PhoneCallIdField.Equals(value) != true)) {
                    this.PhoneCallIdField = value;
                    this.RaisePropertyChanged("PhoneCallId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneCallNr {
            get {
                return this.PhoneCallNrField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneCallNrField, value) != true)) {
                    this.PhoneCallNrField = value;
                    this.RaisePropertyChanged("PhoneCallNr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pin {
            get {
                return this.PinField;
            }
            set {
                if ((object.ReferenceEquals(this.PinField, value) != true)) {
                    this.PinField = value;
                    this.RaisePropertyChanged("Pin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> PrimaryPhoneCallId {
            get {
                return this.PrimaryPhoneCallIdField;
            }
            set {
                if ((this.PrimaryPhoneCallIdField.Equals(value) != true)) {
                    this.PrimaryPhoneCallIdField = value;
                    this.RaisePropertyChanged("PrimaryPhoneCallId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Priority {
            get {
                return this.PriorityField;
            }
            set {
                if ((this.PriorityField.Equals(value) != true)) {
                    this.PriorityField = value;
                    this.RaisePropertyChanged("Priority");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductEvent {
            get {
                return this.ProductEventField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductEventField, value) != true)) {
                    this.ProductEventField = value;
                    this.RaisePropertyChanged("ProductEvent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ScheduledStart {
            get {
                return this.ScheduledStartField;
            }
            set {
                if ((this.ScheduledStartField.Equals(value) != true)) {
                    this.ScheduledStartField = value;
                    this.RaisePropertyChanged("ScheduledStart");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> TimeDifference {
            get {
                return this.TimeDifferenceField;
            }
            set {
                if ((this.TimeDifferenceField.Equals(value) != true)) {
                    this.TimeDifferenceField = value;
                    this.RaisePropertyChanged("TimeDifference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> TypeEvent {
            get {
                return this.TypeEventField;
            }
            set {
                if ((this.TypeEventField.Equals(value) != true)) {
                    this.TypeEventField = value;
                    this.RaisePropertyChanged("TypeEvent");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ActionStatusesData", Namespace="http://schemas.datacontract.org/2004/07/PublicServiceForPartners.DataContracts")]
    [System.SerializableAttribute()]
    public partial class ActionStatusesData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid ActionStatusIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ActionStatusNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsFinalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSpecifyRefusalReasonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TypeActionStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeActionStatusNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ActionStatusId {
            get {
                return this.ActionStatusIdField;
            }
            set {
                if ((this.ActionStatusIdField.Equals(value) != true)) {
                    this.ActionStatusIdField = value;
                    this.RaisePropertyChanged("ActionStatusId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ActionStatusName {
            get {
                return this.ActionStatusNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ActionStatusNameField, value) != true)) {
                    this.ActionStatusNameField = value;
                    this.RaisePropertyChanged("ActionStatusName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsFinal {
            get {
                return this.IsFinalField;
            }
            set {
                if ((this.IsFinalField.Equals(value) != true)) {
                    this.IsFinalField = value;
                    this.RaisePropertyChanged("IsFinal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSpecifyRefusalReason {
            get {
                return this.IsSpecifyRefusalReasonField;
            }
            set {
                if ((this.IsSpecifyRefusalReasonField.Equals(value) != true)) {
                    this.IsSpecifyRefusalReasonField = value;
                    this.RaisePropertyChanged("IsSpecifyRefusalReason");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TypeActionStatus {
            get {
                return this.TypeActionStatusField;
            }
            set {
                if ((this.TypeActionStatusField.Equals(value) != true)) {
                    this.TypeActionStatusField = value;
                    this.RaisePropertyChanged("TypeActionStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TypeActionStatusName {
            get {
                return this.TypeActionStatusNameField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeActionStatusNameField, value) != true)) {
                    this.TypeActionStatusNameField = value;
                    this.RaisePropertyChanged("TypeActionStatusName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestError", Namespace="http://schemas.datacontract.org/2004/07/PublicServiceForPartners.DataContracts")]
    [System.SerializableAttribute()]
    public partial class RequestError : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Code {
            get {
                return this.CodeField;
            }
            set {
                if ((this.CodeField.Equals(value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PhoneCalls.IPhoneCallsService")]
    public interface IPhoneCallsService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhoneCallsService/GetPhoneCalls", ReplyAction="http://tempuri.org/IPhoneCallsService/GetPhoneCallsResponse")]
        action_gw.PhoneCalls.GetPhoneCallsData[] GetPhoneCalls(System.Nullable<System.DateTime> dateStart);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhoneCallsService/GetActionStatusesForCampaignId", ReplyAction="http://tempuri.org/IPhoneCallsService/GetActionStatusesForCampaignIdResponse")]
        action_gw.PhoneCalls.ActionStatusesData[] GetActionStatusesForCampaignId(System.Guid companyId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhoneCallsService/CompletePhoneCall", ReplyAction="http://tempuri.org/IPhoneCallsService/CompletePhoneCallResponse")]
        action_gw.PhoneCalls.RequestError CompletePhoneCall(System.Guid phoneCallId, System.Guid actionStatusId, System.Nullable<System.Guid> declineReasonStatusId, System.Nullable<System.DateTime> nextCallTime);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPhoneCallsServiceChannel : action_gw.PhoneCalls.IPhoneCallsService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PhoneCallsServiceClient : System.ServiceModel.ClientBase<action_gw.PhoneCalls.IPhoneCallsService>, action_gw.PhoneCalls.IPhoneCallsService {
        
        public PhoneCallsServiceClient() {
        }
        
        public PhoneCallsServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PhoneCallsServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PhoneCallsServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PhoneCallsServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public action_gw.PhoneCalls.GetPhoneCallsData[] GetPhoneCalls(System.Nullable<System.DateTime> dateStart) {
            return base.Channel.GetPhoneCalls(dateStart);
        }
        
        public action_gw.PhoneCalls.ActionStatusesData[] GetActionStatusesForCampaignId(System.Guid companyId) {
            return base.Channel.GetActionStatusesForCampaignId(companyId);
        }
        
        public action_gw.PhoneCalls.RequestError CompletePhoneCall(System.Guid phoneCallId, System.Guid actionStatusId, System.Nullable<System.Guid> declineReasonStatusId, System.Nullable<System.DateTime> nextCallTime) {
            return base.Channel.CompletePhoneCall(phoneCallId, actionStatusId, declineReasonStatusId, nextCallTime);
        }
    }
}
